name: basic_flutter
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  dropdown_search: ^5.0.6
  faker: ^2.1.0
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_nav_bar: ^5.0.6
  http: ^1.2.0
  intl: ^0.19.0
  introduction_screen: ^3.1.14
  lottie: ^3.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/cat.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "path/to/image.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
